### ISSUE TITLE
Add Twistlock Security Scanning as Part of CircleCi Configuration

### ISSUE THREAD

**Issue by bama4** [GovReady/govready-q#1079]
**Description**
This issue involves adding twistlock to the `.circleci/config.yml` file to scan code for vulnerabilities automatically

A sample configuration can be found here: https://circleci.com/blog/integrating-container-image-scanning-into-circleci-builds-with-the-twistlock-orb/

Sample config:
```
version: 2.1
orbs:
  twistcli: twistlock/twistcli-scan@1.0.4
jobs:
  docker-build-and-save:
    executor: twistcli/default
    steps:
      - checkout
      - run: 'docker build -t myrepo/myimage:tag .'
      - run: mkdir -p workspace
      - run: 'docker save myrepo/myimage:tag -o workspace/image.tar'
      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar
workflows:
  scan-image:
    jobs:
      - docker-build-and-save
      - twistcli/scan-image:
          requires:
            - docker-build-and-save
          context: tl_scan_context
          image: 'myrepo/myimage:tag'
          imagetar: image.tar
          vuln-thresh: critical
          comp-thresh: ''
          only-fixed: true
```

**Goal**
Twistlock is added to CircleCi for running automatically at each branch push
