### ISSUE TITLE
Bug: "n/a" as a value in imputed values renders as 

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#182]
See `system_name.yaml`

```
  - id: system_abbreviation
    title: System Abbreviation
    prompt: |
      You've indicated a short name or acronym exists for {{project}} system.

      What is the preferred abbreviation or acronym?
    type: text
    impute:
    - condition: system_abbreviation_exists == 'no'
      value: "n/a"
```

<img width="864" alt="screen shot 2016-09-11 at 1 37 29 am" src="https://cloud.githubusercontent.com/assets/24979/18415437/99afbdf6-77c0-11e6-894c-aea8d298c5d3.png">
