### ISSUE TITLE
Template may misinterpret single `#` in markdown of introduction template

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#237]
In `system_name_and_details.yaml`, using a single `#` in template of introduction seems to hide the line instead of making line an `<h1>`.  Using `##` creates a `<h3>` headline.

Replicate as follows:

```
id: system_name_and_details
title: System Name and Details
introduction:
  format: markdown
  template: |
    # System Profile

    An official name makes your system easier to track in documents and databases.

    Let's document the names of the *{{project}}* system for your System Security Plan, plus some basic system information.
```
