### ISSUE TITLE
Better documentation on building and displaying entire documents combining module sub-docs

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#577]
Better documentation is needed to describe the process for compliance app "master" documents such ass SSP's and PTAs that are assembled from sub-modules.

The following instructions are under development and need details and testing. 

### Method 1 for displaying a master document:
1. Create as an `output` within the `app.yaml` file
1. format must be `markdown` or `text`
1. Master documents should show up in the "Documents" action-button
1. Adding `position: action-buttons` will display a button for the document below the action-buttons on the right.

### Method 2 for displaying a master document:
1. Create a module app for the master document
1. Define the master document as an output.
1. Do not have any question questions that need to be answered, or have a dummy question with an imputed answer.
1. The master document module will appear listed with the other modules.

*In the `app.yaml` file:*
```
# Artifacts
- id: pta_form
  title: View PTA Artifact
  type: module
  module-id: pta_form
  placement: action-buttons
```

*In the `pta_form.yaml` app module file:*
```
id: pta_form
title: Privacy Threshold Analysis Artifact
version: 1

questions:
- id: dummy
  title: dummy
  prompt: dummy
  type: raw
  impute:
    - condition: "true"
      value: ~

output:
- format: markdown
  title: Privacy Threshold Analysis
  template: |
     (template content here)
```
