### ISSUE TITLE
Document how to customize compliance app icons and overwrite default icon

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#595]
Add documentation on how to replace the app icon to Read The Docs. 

### Draft Documentation

By convention, every app is bundled with a 128 x 128 pixel icon named `app.png`, e.g. `someapp/assets/app.png`. The app's icon is explicitly referenced in the app's `app.yaml` file.

```
id: app
title: Some App
type: project
version: 0.4.3
icon: app.png
protocol: mycompany.com/assessments/someappcategory
```

It is also possible to use an alternate icon name.

```
id: app
title: Some App
type: project
version: 0.4.3
icon: mycustom.png
protocol: mycompany.com/assessments/someappcategory
```

It's easy and looks nice to display the compliance app's bundled icon next every module by adding an `icon: app.png` value to each question module block in the app's `app.yaml` file.

```
questions:

- id: summary_info
  title: Summary Information
  type: module
  module-id: summary_info
  icon: app.png

- id: notices
  title: Notices
  type: module
  module-id: notices
  icon: app.png
```

When the compliance app is bundled with multiple images in the `assets` directory (`someapp/assets/app.png`, `someapp/assets/mysummaryicon.png`, `someapp/assets/mysummaryicon.pngmyothericon.png`...), individual question modules can display different icons by referencing different image files located in the app's `assets` directory. 

```
questions:

- id: summary_info
  title: Summary Information
  type: module
  module-id: summary_info
  icon: mysummaryicon.png

- id: notices
  title: Notices
  type: module
  module-id: notices
  icon: myothericon.png
```
